### ISSUE TITLE
Attempting to change configuration ':compile' after it has been included in dependency resolution.

### ISSUE THREAD

**Issue by musketyr** [erdi/gaelyk-functional-test#1]
see https://github.com/gaelyk/gaelyk/issues/219

**Comment by erdi** [comment]
@musketyr, this has nothing to do with this helper library. It is the gradle-appengine-plugin that [adds the functionalTestCompile configuration](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/blob/f185f4a0fb13cc381b324320cd3f2a5a932e65ae/src/main/groovy/com/google/appengine/AppEnginePlugin.groovy#L694). After having a look at the code that was initially written by me I believe, I have not been able to spot why this warning is emitted.

It's probably best to ask at Gradle forums or do what @alkemist suggests in [this comment](https://discuss.gradle.org/t/gradle-2-2-rc-1-is-now-available-for-testing/7753/14) but for `compile` instead of `default` and see if you will be able to spot what is closing that configuration eagerly. Also, I don't understand why adding something to a configuration (`functionalTestCompile`) would modify a configuration it extends from (`testCompile`).

**Comment by musketyr** [comment]
oh, sorry. I'll continue there.
